#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Componente.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Standby")]
	public partial class DataComponenteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataComponenteDataContext() : 
				base(global::Componente.AccesoDatos.Properties.Settings.Default.StandbyConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataComponenteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataComponenteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataComponenteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataComponenteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Login_Consulta")]
		public ISingleResult<Login_ConsultaResult> Login_Consulta()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Login_ConsultaResult>)(result.ReturnValue));
		}
	}
	
	public partial class Login_ConsultaResult
	{
		
		private int _Id;
		
		private string _Login;
		
		private char _Estado;
		
		private System.DateTime _Fecha_Ingreso;
		
		private string _Usuario_Ingreso;
		
		private System.Nullable<System.DateTime> _Fecha_Actualiza;
		
		private string _Usuario_Actualiza;
		
		public Login_ConsultaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this._Login = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Ingreso", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Usuario_Ingreso
		{
			get
			{
				return this._Usuario_Ingreso;
			}
			set
			{
				if ((this._Usuario_Ingreso != value))
				{
					this._Usuario_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Actualiza
		{
			get
			{
				return this._Fecha_Actualiza;
			}
			set
			{
				if ((this._Fecha_Actualiza != value))
				{
					this._Fecha_Actualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Actualiza", DbType="Char(50)")]
		public string Usuario_Actualiza
		{
			get
			{
				return this._Usuario_Actualiza;
			}
			set
			{
				if ((this._Usuario_Actualiza != value))
				{
					this._Usuario_Actualiza = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
